cert:
  url_base_api: 
homol:
  db:
  teste:                          "cliente"
  servico_salvar_doc:
    cliente:                      "SalvarDocumentoCliente"
    extratocobranca:              "SalvarDocumentoExtratoCobranca"
    multa:                        "SalvarDocumentoMulta"
    notadebito:                   "SalvarDocumentoNotaDebito"
    ra:                           "SalvarDocumentoRA"
    reserva:                      "SalvarDocumentoReserva"
    notacredito:                  "SalvarDocumentoNotaCredito"
    ficha:                        "SalvarDocumentoFicha"
  servico_consultar_imagem:
    cliente:                      "ConsultarDocumentoCliente"
    extratocobranca:              "ConsultarDocumentoExtratoCobranca"
    multa:                        "ConsultarDocumentoMulta"
    notadebito:                   "ConsultarDocumentoNotaDebito"
    ra:                           "ConsultarDocumentoRA"
    reserva:                      "ConsultarDocumentoReserva"    
    notacredito:                  "ConsultarDocumentoNotaCredito"
    ficha:                        "ConsultarDocumentoFicha"          
  tabelas:
    documento:                    "tblDocumento"
    cliente:                      "tblDocumentoCliente"
    paginas:                      "tblDocumentoPagina"
    extratocobranca:              "tblDocumentoExtratoCobranca"
    historico:                    "tblDocumentoHistorico"
    multa:                        "tblDocumentoMulta"
    notadebito:                   "tblDocumentoNotaDebito"
    ra:                           "tblDocumentoRA"
    reserva:                      "tblDocumentoReserva"
    status:                       "tblDocumentoStatus"
    tipo:                         "tblDocumentoTipo"
    tipoprocessamento:            "tblDocumentoTipoProcessamento"
  chave:
    cliente:                      "CLIDOC"
    extratocobranca_prasig:       "PRASIG"
    extratocobranca_fatnumseq:    "FATNUMSEQ"
    extratocobranca_fatser:       "FATSER"
    multa:                        "MULAUT"
    reserva_resnum:               "RESNUM"
    reserva_reslojope:            "RESLOJOPE"
    notadebito_prasig:            "PRASIG"
    notadebito_fatdebnum:         "FATDEBNUM"
    ra_r_anum:                    "R_ANUM"
    ra_r_alojret:                 "R_ALOJRET"
  ids:
    cliente:                      "3602"
    extratocobranca_prasig:       "33331"
    extratocobranca_fatnumseq:    "33331"
    extratocobranca_fatser:       "33331"
    multa:                        "444"
    notadebito_prasig:            "555"
    notadebito_fatdebnum:         "555"
    ra_r_anum:                    "666"
    ra_r_alojret:                 "666"
    reserva_resnum:               "777"
    reserva_reslojope:            "777"      
    documentotipo_id_cliente:           "1" #cliente= 1, 2 ou 3
    documentotipo_id_reserva:           "4" #reserva = 4
    documentotipo_id_multa:             "5" #multa = 5
    documentotipo_id_notadebito:        "6" #notadebito = 6
    documentotipo_id_ra:                "7" #RA = 7
    documentotipo_id_extratocobranca:   "8" #ExtratoCobranca = 8
    documento_status_id:                "2" # 0 = A processar / 1 = Documento Preparado / 2 = Tempo Real
prod:
  url_base_api: